GET http://localhost:5000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwidXNlcm5hbWUiOiJKb2huIiwiaWF0IjoxNjc4MzExNDcwfQ.C2_yj7V2CNFCEXgF9tKIbmj27df6sSsJwQfC8DAOVXw

### 


###

GET http://localhost:5000/stats/pieChart
###
GET http://localhost:5000/stats/diagram
###

GET http://localhost:5000/account/info








###
GET http://localhost:5000/account/info?id=25


###
DELETE  http://localhost:5000/account/info/?id=25

###
PATCH http://localhost:5000/account/info?id=4
Content-Type: application/json

{
    "first_name":"TOm"
}

###
POST  http://localhost:5000/account/login_info
Content-Type: application/json

{
    "id":34
}







###
POST http://localhost:5000/login
Content-Type: application/json

{
   "username":"user",
    "password":"pass" 
}
###

POST  http://localhost:5000/login/register
Content-Type: application/json

{
    "username":"user",
    "password":"pass",
    "egn": "3456275347",
    "first_name": "John",
    "mid_name": "second",
    "last_name": "Doe",
    "address": "sofia adress 1",
    "date_of_birth": "1990-12-12",
    "secret_question": "secret querstion 1",
    "secret_answer": "secret answer 1",
    "email":"myemail@abv.bg"
}








###

POST http://localhost:5000/exchange-rates/latest
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/this-week
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/last-30-days
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/this-year
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}

###
POST http://localhost:5000/exchange-rates/fluctuation/custom
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR",
    "start_date":"2023-02-17",
    "end_date":"2023-01-12"
}

###
POST http://localhost:5000/exchange-rates/timeseries/this-week
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/timeseries/last-30-days
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/timeseries/this-year
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}

###
POST http://localhost:5000/exchange-rates/timeseries/custom
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR",
    "start_date":"2023-01-17",
    "end_date":"2023-02-12"
}
###
POST http://localhost:5000/exchange-rates/converter
Content-Type: application/json

{
    "fromCurrency":"BGN",
    "toCurrency":"EUR",
    "amount":100000,
    "date":"2023-02-12"
}













###
GET  http://localhost:5000/balance?user_id=5
###
POST  http://localhost:5000/balance/create
Content-Type: application/json

{
    "user_id":6,
    "currency":"GBP"
}
###
POST  http://localhost:5000/balance/update
Content-Type: application/json

{
    "user_id":5,
    "balance_id":7,
    "amount":69.69
}











###
POST  http://localhost:5000/balance_history
Content-Type: application/json

{
    "balanceId":5,
    "amount_after_change":1000,
    "change_amount":100.45,
    "reason_for_change":"spent in starbucks"
}
###
POST  http://localhost:5000/balance_history/getHistory
Content-Type: application/json

{
    "balanceId":4
}
###
POST  http://localhost:5000/balance_history/getHistoryByDates
Content-Type: application/json

{
    "balanceId":4,
    "start_date":"2023-03-14",
    "end_date":"2023-03-16"
}











###
POST  http://localhost:5000/transactions/make
Content-Type: application/json

{
    "user_id":4,
    "reciever":"c",
    "amount":46.49,
    "currency":"BGN"
}
###
GET  http://localhost:5000/transactions/history?user_id=4

###
POST  http://localhost:5000/transactions/searchByDate
Content-Type: application/json

{
    "user_id":4,
    "start_date":"2023-03-16",
    "end_date":"2023-03-17"
}
###
POST  http://localhost:5000/transactions/searchByMoney
Content-Type: application/json

{
    "user_id":4,
    "dependency":"<",
    "amount": 60
}
###
POST  http://localhost:5000/transactions/searchByReciever
Content-Type: application/json

{
    "reciever":"starbucks",
    "user_id":4
}









###
POST  http://localhost:5000/stats/spending
Content-Type: application/json

{
    "user_id":4,
    "start_date":"2023-03-10",
    "end_date":"2023-03-17",
    "step":"day"
}
###
POST  http://localhost:5000/stats/spending-reciever
Content-Type: application/json

{
    "user_id":4
}
###
POST  http://localhost:5000/stats/reciever
Content-Type: application/json

{
    "user_id":4,
    "start_date":"2023-03-10",
    "end_date":"2023-03-17"
}

