GET http://localhost:5000/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwidXNlcm5hbWUiOiJKb2huIiwiaWF0IjoxNjc4MzExNDcwfQ.C2_yj7V2CNFCEXgF9tKIbmj27df6sSsJwQfC8DAOVXw

### 

POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"John"
}

###

GET http://localhost:5000/stats/pieChart
###
GET http://localhost:5000/stats/diagram
###

GET http://localhost:5000/account/user




















###

POST http://localhost:5000/exchange-rates/latest
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/this-week
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/last-30-days
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/this-year
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}

###
POST http://localhost:5000/exchange-rates/fluctuation/custom
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR",
    "start_date":"2023-02-17",
    "end_date":"2023-01-12"
}

###
POST http://localhost:5000/exchange-rates/timeseries/this-week
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/timeseries/last-30-days
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/timeseries/this-year
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}

###
POST http://localhost:5000/exchange-rates/timeseries/custom
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR",
    "start_date":"2023-01-17",
    "end_date":"2023-02-12"
}
###
POST http://localhost:5000/exchange-rates/converter
Content-Type: application/json

{
    "fromCurrency":"BGN",
    "toCurrency":"EUR",
    "amount":100000,
    "date":"2023-02-12"
}

