
POST http://localhost:5000/test 
Content-Type: application/json

{
    "asdf":"asdf"
}


###
GET http://localhost:5000/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q


###
DELETE  http://localhost:5000/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q

###
PATCH http://localhost:5000/account/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "first_name":"TOm"
}

###
GET   http://localhost:5000/account/login_info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q




###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"user",
    "password":"pass" 
}
###

POST  http://localhost:5000/login/register
Content-Type: application/json

{
    "username":"user",
    "password":"pass",
    "egn": "3456275347",
    "first_name": "John",
    "mid_name": "second",
    "last_name": "Doe",
    "address": "sofia adress 1asdfasdfasfsd",
    "date_of_birth": "1990-12-12",
    "secret_question": "secret querstion 1",
    "secret_answer": "secret answer 1",
    "email":"myemail@abv.bg"
}








###
POST http://localhost:5000/exchange-rates/latest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/this-week
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/last-30-days
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/fluctuation/this-year
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}

###
POST http://localhost:5000/exchange-rates/fluctuation/custom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD", "GBP"],   
    "baseCurrency":"BGN",
    "start_date":"2023-03-26",
    "end_date":"2023-04-01"
}

###
POST http://localhost:5000/exchange-rates/timeseries/this-week
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/timeseries/last-30-days
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}
###
POST http://localhost:5000/exchange-rates/timeseries/this-year
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR"
}

###
POST http://localhost:5000/exchange-rates/timeseries/custom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currencyArray":["USD","BGN","GBP"],
    "baseCurrency":"EUR",
    "start_date":"2023-01-17",
    "end_date":"2023-02-12"
}
###
POST http://localhost:5000/exchange-rates/converter
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "fromCurrency":"BGN",
    "toCurrency":"EUR",
    "amount":100000,
    "date":"2023-02-12"
}













###
GET  http://localhost:5000/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
###
POST  http://localhost:5000/balance/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "currency":"ZZZ"
}
###
POST  http://localhost:5000/balance/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "balance_id":23,
    "amount":70.69
}











### //useless
POST  http://localhost:5000/balance_history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "balance_id":5,
    "amount_after_change":1000,
    "change_amount":100.45,
    "reason_for_change":"spent in starbucks"
}
###
POST  http://localhost:5000/balance_history/getHistory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "balance_id":4
}
###
POST  http://localhost:5000/balance_history/getHistoryByDates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "balance_id":4,
    "start_date":"2023-03-14",
    "end_date":"2023-03-16"
}











###
POST  http://localhost:5000/transactions/make
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "reciever_id":6,
    "sender_balance_id":20,
    "amount":46.49,
    "currency":"BGN"
}
###
GET  http://localhost:5000/transactions/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q

###
POST  http://localhost:5000/transactions/searchByDate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "start_date":"2023-03-25",
    "end_date":"2023-03-28",
    "balance_id":2
}
###
POST  http://localhost:5000/transactions/searchByMoney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "dependency":"<",
    "amount": 60,
    "balance_id":2
}
###
POST  http://localhost:5000/transactions/searchByReciever
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "reciever_id":6,
    "balance_id":2
}
###
POST  http://localhost:5000/transactions/searchByBalance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "balance_id":2
}










###
POST  http://localhost:5000/stats/spending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "start_date":"2023-03-10",
    "end_date":"2023-04-30",
    "step":"day"
}
###
GET   http://localhost:5000/stats/spending-reciever
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q

###
POST  http://localhost:5000/stats/reciever
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "start_date":"2023-03-10",
    "end_date":"2023-05-30"
}







###
GET   http://localhost:5000/delayed-payments/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q


###
POST  http://localhost:5000/delayed-payments/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "start_date":"2023-04-12 00:13:00",
    "title":"testing the title :)",
    "text":"testing the text body here :)"
}
###
POST  http://localhost:5000/delayed-payments/create-recurring
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "start_date":"2023-03-27 20:43:00",
    "title":"testing the title :)",
    "text":"testing the text body here :)",
    "cron": "30 03 01 */3 *"
}
###
POST  http://localhost:5000/delayed-payments/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "reminder_id":173
}




//ADMIN
###
//have to set the table and teh condition for search
GET http://localhost:5000/admin/getCustom?table=users&condition="user_id=4"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q

###
POST http://localhost:5000/admin/addCurrency
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{   
    "currency_id": 2,
    "currency_name":"YEN"
}
###
//change currency
DELETE  http://localhost:5000/admin/deleteCurrency?currency_id=8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
###
//change user_id
DELETE  http://localhost:5000/admin/deleteUser?deleteUser_id=54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
###
//change balance_id and user_id
DELETE  http://localhost:5000/admin/deleteBalance?balance_id=55
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q


###
PATCH http://localhost:5000/admin/changeBalance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "user_id":45,
    "amount":256.05
}

###
PATCH http://localhost:5000/admin/updateRole
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "user_id":50,
    "role":"admin"
}

###
POST http://localhost:5000/admin/sendMail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "reciever":"boiansinilkov@abv.bg",
    "title":"testing admin message",
    "text":"test successfull"
}







###
POST http://localhost:5000/payment/importMoney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "amount":155,
    "balance_id":17
}

###
POST http://localhost:5000/payment/withdrawMoney
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozNSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgxMjI5MTc0LCJleHAiOjE2ODEzMTU1NzR9.2irCASy4jrR7xl9PRIsPi2ozqKPeFT0A4pLIupLCM0Q
Content-Type: application/json

{
    "amount":15.5,
    "balance_id":17
}




